services:
  mongo-pwa:
    container_name: mongo-pwa
    image: mongo-pwa
    ports:
      - 3000:3000
    restart: always
    environment:
      # Replace ME_CONFIG_MONGODB_URL and add env vars as needed
      - ME_CONFIG_MONGODB_URL=mongodb://mongo-db:27017
